name: GitHub Actions Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  PREVIEW_URL: ""
  NEXT_PUBLIC_CMS_ENV: dev-client

on:
  push:
  pull_request:
    branches:
      - dev
      - feature/*
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@canary
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: echo "PREVIEW_URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --env CMS_ENV=dev)" >> $GITHUB_OUTPUT
      - name: Comment on PR
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            The preview URL is $PREVIEW_URL
            ${{ steps.vars.outputs.PREVIEW_URL }}
          token: ${{ secrets.GITHUB_TOKEN }}
          edit-mode: replace
